### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by oliver216**
Add the dark mode version to be always visible (so no more light mode).
Corrected a bug that crashed the app if when entering a link nothing was input. add the possibility to close this input without filling it. Change some small UI option to have a better render.

### CODE REVIEW

**Review by Freezemoon — COMMENTED** [review]
Very small PR so nothing much to say, I'm just not sure why forcing the dark mode ?

**Comment by oliver216** [comment]
I force the dark mode of the app (not the other interface of the phone) because we haven't coded for the light mode. (We juste have standard color for it that don't really fit and are not supposed to be used for our app.

**Comment by Freezemoon** [comment]
Ohhhh i havent touched the UI so I didnt know, thanks for telling me!

**Review by Freezemoon — APPROVED** [review]
Looks all good!

**Pull request merged**
